# **Data Preprocessing**

In [ ]:
import json
import numpy as np
import pandas as pd
import os
import re
import pickle
import nltk
from mlxtend.plotting import plot_confusion_matrix
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB


In [3]:
User_id = []
Bus_id = []
Star = []
Useful = []
Funny = []
Cool = []
Text = []
I=1

In [4]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ndavidson/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/ndavidson/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/ndavidson/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [338]:
DF_Final = pd.read_csv('./Downloads/Data_Final')

In [99]:
documents = []
X = DF_Final.Review
stemmer = WordNetLemmatizer()
for i in range(0, len(X)):
    # Remove all the special characters, like parathesis
    document = re.sub(r'\W', ' ', str(X[i]))
    # remove all single characters: like a, b, c, d
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document)
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    # Converting to Lowercase
    document = document.lower()
    # Lemmatization
    document = document.split()
    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    documents.append(document)

In [100]:
vectorizer = CountVectorizer(max_features=1500, min_df=0.1, max_df=0.7, 
stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [101]:
f_n = open("./Downloads/negative-words.txt", "r")
Negative_words = f_n.readlines()
f_p = open("./Downloads/positive-words.txt", "r")
Positive_words = f_p.readlines()
Voca = [i.rstrip('\n') for i in Positive_words] + [i.rstrip('\n') for i in 
Negative_words]
vectorizer = CountVectorizer(vocabulary=np.unique(Voca))
X = vectorizer.fit_transform(documents).toarray()

In [42]:
DF_Final.head()

Unnamed: 0                 User_id                  Bus_id  Star  Useful  \
0           0  4hBhtCSgoxkrFgHa4YAD-w  bbEXAEFr4RYHLlZ-HFssTA   5.0       0   
1           1  JYYYKt6TdVA4ng9lLcXt_g  SZU9c8V2GuREDN5KgyHFJw   5.0       0   
2           2  Uk3X2AypU8AqvcYEVf7s6Q  eL4lyE7LNoXEMvpcJ8WNVw   3.0       5   
3           3  LcqNuhqaYt5ekKzaRirmIg  SZU9c8V2GuREDN5KgyHFJw   5.0       2   
4           4  gasLVm0KRwrVhPGRcqATjw  CHh0ZFrQcsk4boOItr2Zuw   4.0       1   

   Cool  Funny                                             Review State  \
0     0      0  Great burgers,fries and salad!  Burgers have a...    CA   
1     0      0  We were a bit weary about trying the Shellfish...    CA   
2     0      0  This was a tough one!   On the merits of the w...    CA   
3     1      0  I love trying fresh seafood on piers, wharfs a...    CA   
4     2      0  I stopped in because I was hungry for some sna...    CA   

            City  Bus_Ave_Star  User_Review_count  User_Useful_count  \
0         Goleta           4.0                922               1687   
1  Santa Barbara           4.0                338                800   
2  Santa Barbara           4.0                431               2126   
3  Santa Barbara           4.0                258                452   
4    Carpinteria           3.0               1638               2658   

   User_Funny_count  User_Cool_count  \
0               694             1070   
1               144              353   
2              1245             1476   
3               125              183   
4               933             2297   

                                               Elite  User_Fans  \
0                2015,2016,2017,2018,2019,20,20,2021         51   
1  2012,2013,2014,2015,2016,2017,2018,2019,20,20,...         30   
2  2012,2013,2014,2015,2016,2017,2018,2019,20,20,...         76   
3                                     2015,2016,2017         37   
4           2014,2015,2016,2017,2018,2019,20,20,2021        105   

   Users_Ave_Star  
0            4.20  
1            4.12  
2            4.05  
3            3.99  
4            3.79

In [102]:
DF_Final['Star']=np.where(DF_Final['Star']>3)
positive_reviews=DF_Final[DF_Final['Star']==1]
negative_reviews=DF_Final[DF_Final['Star']==0]

ValueError: Length of values (1) does not match length of index (53845)

In [107]:
DF_Final['Star'] = (DF_Final['Star']>3).astype(int)

In [108]:
DF_Final

Unnamed: 0                 User_id                  Bus_id  Star  \
0               0  4hBhtCSgoxkrFgHa4YAD-w  bbEXAEFr4RYHLlZ-HFssTA     1   
1               1  JYYYKt6TdVA4ng9lLcXt_g  SZU9c8V2GuREDN5KgyHFJw     1   
2               2  Uk3X2AypU8AqvcYEVf7s6Q  eL4lyE7LNoXEMvpcJ8WNVw     0   
3               3  LcqNuhqaYt5ekKzaRirmIg  SZU9c8V2GuREDN5KgyHFJw     1   
4               4  gasLVm0KRwrVhPGRcqATjw  CHh0ZFrQcsk4boOItr2Zuw     1   
...           ...                     ...                     ...   ...   
53840       53840  wuxZSSVXwKzN3NPcdSljUA  q0DRuEAxE5i57xNSTrDP4Q     0   
53841       53841  ZDCWEctaQHfJQT1sH_rMmA  rZQqiElaeM7JO2rQAXHK2w     1   
53842       53842  ZDCWEctaQHfJQT1sH_rMmA  EA4v61tJCHg8xhk7bqn8Yw     1   
53843       53843  SSlW0LTQwER5obHjTW0ZIg  3tvi-OJ_-iK1ecjzSaH-oA     1   
53844       53844  nxpp3uivlQw8x-vfTw0Gyg  ak-RiYgUZzM_90c8ONWFzw     1   

       Useful  Cool  Funny                                             Review  \
0           0     0      0  Great burgers,fries and salad!  Burgers have a...   
1           0     0      0  We were a bit weary about trying the Shellfish...   
2           5     0      0  This was a tough one!   On the merits of the w...   
3           2     1      0  I love trying fresh seafood on piers, wharfs a...   
4           1     2      0  I stopped in because I was hungry for some sna...   
...       ...   ...    ...                                                ...   
53840       2     0      2  So let me begin by stating that the owner of N...   
53841       3     2      2  We've used Jerry The Plumber for water heater ...   
53842       2     2      0  Wow, talk about some of the best deals I've ev...   
53843       4     3      2  My Husband and I decided to stop into Hook and...   
53844       2     2      1  We have asked Burgundy Blue to capture over 5 ...   

      State           City  Bus_Ave_Star  User_Review_count  \
0        CA         Goleta           4.0                922   
1        CA  Santa Barbara           4.0                338   
2        CA  Santa Barbara           4.0                431   
3        CA  Santa Barbara           4.0                258   
4        CA    Carpinteria           3.0               1638   
...     ...            ...           ...                ...   
53840    CA     Isla Vista           3.5                227   
53841    CA  Santa Barbara           4.5                691   
53842    CA  Santa Barbara           4.5                691   
53843    CA  Santa Barbara           4.5                163   
53844    CA  Santa Barbara           5.0                248   

       User_Useful_count  User_Funny_count  User_Cool_count  \
0                   1687               694             1070   
1                    800               144              353   
2                   2126              1245             1476   
3                    452               125              183   
4                   2658               933             2297   
...                  ...               ...              ...   
53840                360               153              133   
53841               2353               427             1361   
53842               2353               427             1361   
53843                391               155              286   
53844                358               110              158   

                                                   Elite  User_Fans  \
0                    2015,2016,2017,2018,2019,20,20,2021         51   
1      2012,2013,2014,2015,2016,2017,2018,2019,20,20,...         30   
2      2012,2013,2014,2015,2016,2017,2018,2019,20,20,...         76   
3                                         2015,2016,2017         37   
4               2014,2015,2016,2017,2018,2019,20,20,2021        105   
...                                                  ...        ...   
53840           2014,2015,2016,2017,2018,2019,20,20,2021         11   
53841                     2016,2017,2018,2019,20,20

# **Train a Naive Bayes Classifier**

In [339]:
#80-10-10 split of train test
test = DF_Final[(DF_Final['Star'] == 1.0) | (DF_Final['Star'] == 5.0)]
Y = DF_Final['Star']
X_train, X_rem, Y_train, Y_rem = train_test_split(X, Y, train_size=0.8)
X_valid, X_test, Y_valid, Y_test = train_test_split(X_rem, Y_rem, test_size=0.5)

print(X_train.shape)
print(X_valid.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_valid.shape)
print(Y_test.shape)
print(test.shape)


(43076, 6786)
(5384, 6786)
(5385, 6786)
(43076,)
(5384,)
(5385,)
(23285, 18)


In [125]:
Users_Avg_Star = DF_Final['Users_Ave_Star']
Bus_Avg_Star = DF_Final['Bus_Ave_Star']
scaler1 = Users_Avg_Star / 5
scaler2 = Bus_Avg_Star / 5

In [144]:
classifier = MultinomialNB()
classifier.fit(X_train, Y_train)

MultinomialNB()

In [174]:
test_X = []
for i in range(len(X)):
    test_X.append(X[i] * ((scaler1[i] + scaler2[i]) / 2)) 


In [176]:
X_test_train, X_test_test, Y_train, Y_test = train_test_split(test_X, Y, train_size=0.8)

In [159]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_test_train, Y_train)

MultinomialNB()

In [160]:
preds1 = classifier.predict(X_test_test)

In [148]:
preds2 = classifier.predict(X_rem)

In [161]:
### With both coefficients
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(Y_test, preds1))
print('\n')
print(classification_report(Y_test, preds1))

[[1436 1324]
 [ 480 7529]]


              precision    recall  f1-score   support

           0       0.75      0.52      0.61      2760
           1       0.85      0.94      0.89      8009

    accuracy                           0.83     10769
   macro avg       0.80      0.73      0.75     10769
weighted avg       0.82      0.83      0.82     10769



In [150]:
### With no coefficients
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(Y_rem, preds2))
print('\n')
print(classification_report(Y_rem, preds2))

[[1546 1155]
 [ 637 7431]]


              precision    recall  f1-score   support

           0       0.71      0.57      0.63      2701
           1       0.87      0.92      0.89      8068

    accuracy                           0.83     10769
   macro avg       0.79      0.75      0.76     10769
weighted avg       0.83      0.83      0.83     10769



In [166]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(max_iter=1000)

In [171]:
logisticRegr.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [172]:
predictions = logisticRegr.predict(X_rem)

In [173]:
print(confusion_matrix(Y_rem, predictions))
print('\n')
print(classification_report(Y_rem, predictions))

[[1434 1278]
 [ 494 7563]]


              precision    recall  f1-score   support

           0       0.74      0.53      0.62      2712
           1       0.86      0.94      0.90      8057

    accuracy                           0.84     10769
   macro avg       0.80      0.73      0.76     10769
weighted avg       0.83      0.84      0.83     10769



In [178]:
logisticRegr2 = LogisticRegression(max_iter=1000)

In [179]:
logisticRegr2.fit(X_test_train, Y_train)

LogisticRegression(max_iter=1000)

In [180]:
predictions2 = logisticRegr.predict(X_test_test)

In [182]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(Y_test, predictions2))
print('\n')
print(classification_report(Y_test, predictions2))

[[1435 1353]
 [ 307 7674]]


              precision    recall  f1-score   support

           0       0.82      0.51      0.63      2788
           1       0.85      0.96      0.90      7981

    accuracy                           0.85     10769
   macro avg       0.84      0.74      0.77     10769
weighted avg       0.84      0.85      0.83     10769



# If a review is useful

In [199]:
DF_Final['User_Useful_count'].describe()

count     53845.000000
mean       2278.217866
std        6293.197684
min          14.000000
25%         276.000000
50%         582.000000
75%        1795.000000
max      206296.000000
Name: User_Useful_count, dtype: float64

In [200]:
DF_Final['Useful'].describe()

count    53845.000000
mean         2.923094
std          7.773329
min          0.000000
25%          0.000000
50%          1.000000
75%          3.000000
max        207.000000
Name: Useful, dtype: float64

In [231]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=0.1, max_df=0.7, 
stop_words=stopwords.words('english'))
tester = vectorizer.fit_transform(documents).toarray()
len(tester)

53845

In [332]:
DF_Final = pd.read_csv('./Downloads/Data_Final')

In [333]:
DF_Final['Useful'] = (DF_Final['Useful']>5).astype(int)
Y_useful = DF_Final['Useful']
Usefullness = DF_Final['User_Useful_count']
scaler3 = Usefullness / 206296
scaled_useful = []
for i in range(len(tester)):
    scaled_useful.append(tester[i] * scaler3[i]) 
useful = tester

In [334]:
scaled_useful_train, scaled_useful_test, Y_scaled_useful_train, Y_scaled_useful_test = train_test_split(scaled_useful, Y_useful, train_size=0.8)
useful_train, useful_test, Y_useful_train, Y_useful_test = train_test_split(useful, Y_useful, train_size=0.8)

In [335]:
use_classifier_with_scalar = MultinomialNB()
use_classifier_with_scalar.fit(scaled_useful_train, Y_scaled_useful_train)
use_classifier = MultinomialNB()
use_classifier.fit(useful_train, Y_useful_train)

MultinomialNB()

In [336]:
scaled_use_preds = use_classifier_with_scalar.predict(scaled_useful_test)
use_preds = use_classifier.predict(useful_test)

# We want to minimize the amount of False Negative
## This is because we would rather have 

In [295]:
print(confusion_matrix(Y_scaled_useful_test, scaled_use_preds))
print('\n')
print(classification_report(Y_scaled_useful_test, scaled_use_preds))

[[9745    0]
 [1023    1]]


              precision    recall  f1-score   support

           0       0.90      1.00      0.95      9745
           1       1.00      0.00      0.00      1024

    accuracy                           0.91     10769
   macro avg       0.95      0.50      0.48     10769
weighted avg       0.91      0.91      0.86     10769



In [296]:
print(confusion_matrix(Y_useful_test, use_preds))
print('\n')
print(classification_report(Y_useful_test, use_preds))
#6

[[9540  167]
 [ 952  110]]


              precision    recall  f1-score   support

           0       0.91      0.98      0.94      9707
           1       0.40      0.10      0.16      1062

    accuracy                           0.90     10769
   macro avg       0.65      0.54      0.55     10769
weighted avg       0.86      0.90      0.87     10769



In [302]:
print(confusion_matrix(Y_useful_test, use_preds))
print('\n')
print(classification_report(Y_useful_test, use_preds))
#7

[[9771  150]
 [ 748  100]]


              precision    recall  f1-score   support

           0       0.93      0.98      0.96      9921
           1       0.40      0.12      0.18       848

    accuracy                           0.92     10769
   macro avg       0.66      0.55      0.57     10769
weighted avg       0.89      0.92      0.90     10769



In [319]:
print(confusion_matrix(Y_useful_test, use_preds))
print('\n')
print(classification_report(Y_useful_test, use_preds))
#8

[[9910  132]
 [ 657   70]]


              precision    recall  f1-score   support

           0       0.94      0.99      0.96     10042
           1       0.35      0.10      0.15       727

    accuracy                           0.93     10769
   macro avg       0.64      0.54      0.56     10769
weighted avg       0.90      0.93      0.91     10769



In [313]:
print(confusion_matrix(Y_useful_test, use_preds))
print('\n')
print(classification_report(Y_useful_test, use_preds))
#9

[[10028   124]
 [  560    57]]


              precision    recall  f1-score   support

           0       0.95      0.99      0.97     10152
           1       0.31      0.09      0.14       617

    accuracy                           0.94     10769
   macro avg       0.63      0.54      0.55     10769
weighted avg       0.91      0.94      0.92     10769



In [325]:
print(confusion_matrix(Y_useful_test, use_preds))
print('\n')
print(classification_report(Y_useful_test, use_preds))
#3

[[8156  408]
 [1796  409]]


              precision    recall  f1-score   support

           0       0.82      0.95      0.88      8564
           1       0.50      0.19      0.27      2205

    accuracy                           0.80     10769
   macro avg       0.66      0.57      0.58     10769
weighted avg       0.75      0.80      0.76     10769



In [331]:
print(confusion_matrix(Y_useful_test, use_preds))
print('\n')
print(classification_report(Y_useful_test, use_preds))
#4

[[8756  322]
 [1436  255]]


              precision    recall  f1-score   support

           0       0.86      0.96      0.91      9078
           1       0.44      0.15      0.22      1691

    accuracy                           0.84     10769
   macro avg       0.65      0.56      0.57     10769
weighted avg       0.79      0.84      0.80     10769



In [337]:
print(confusion_matrix(Y_useful_test, use_preds))
print('\n')
print(classification_report(Y_useful_test, use_preds))
#5

[[9234  211]
 [1156  168]]


              precision    recall  f1-score   support

           0       0.89      0.98      0.93      9445
           1       0.44      0.13      0.20      1324

    accuracy                           0.87     10769
   macro avg       0.67      0.55      0.56     10769
weighted avg       0.83      0.87      0.84     10769



In [ ]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,Y_train)
pred_3=svm.predict(cv.transform(X_rem))
score_3=accuracy_score(Y_rem,pred_3)

In [ ]:
print(score_3*100)

In [ ]:
cm = confusion_matrix(y_test, pred_3)
plt.figure()
plot_confusion_matrix(cm, figsize=(12,8), hide_ticks=True, cmap=plt.cm.Blues)
plt.title("Support Vector Machine - Confusion Matrix")
plt.xticks(range(2), ["Positve Review","Negative Review"], fontsize=16)
plt.yticks(range(2), ["Positive Review","Negative Review"], fontsize=16)
plt.show()